# Generated by Django 2.2.5 on 2020-05-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProjet', models.CharField(max_length=300)),
                ('nbJourHomme', models.IntegerField()),
                ('experiencesLiees', models.ManyToManyField(to='collab.competences')),
            ],
        ),
    ]
