# Generated by Django 2.2.5 on 2020-05-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0004_auto_20200511_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateurs',
            name='codePostal',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='collaborateurs',
            name='mail',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='collaborateurs',
            name='telephone',
            field=models.CharField(default='', max_length=200),
        ),
    ]
