# Generated by Django 2.2.5 on 2020-05-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0005_auto_20200511_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateurs',
            name='typeContrat',
            field=models.CharField(choices=[('I', 'Interne'), ('E', 'Externe')], default='I', max_length=1),
        ),
    ]
