# Generated by Django 2.2.5 on 2020-05-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0006_collaborateurs_typecontrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateurs',
            name='tjm',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
