# Generated by Django 2.2.5 on 2020-05-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0008_collaborateurs_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='contexteMission',
            field=models.TextField(default=''),
        ),
    ]
