# Generated by Django 2.2.5 on 2020-05-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0009_projet_contextemission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiences',
            name='contexteMission',
        ),
    ]
