# Generated by Django 2.2.5 on 2020-05-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0010_remove_experiences_contextemission'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='contexteMission',
            field=models.TextField(default=''),
        ),
    ]
