# Generated by Django 3.0.5 on 2020-05-26 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0011_experiences_contextemission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomBU', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Business Unit',
            },
        ),
        migrations.CreateModel(
            name='langue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomLangue', models.CharField(max_length=500)),
                ('niveauLangue', models.CharField(choices=[('A0', 'Débutant'), ('A1', 'Élémentaire'), ('A2', 'Pré-intermédiaire'), ('B1', 'Intermédiaire'), ('B2', 'Intermédiaire supérieur'), ('C1', 'Avancé'), ('C2', 'Courant')], default='A0', max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='collaborateurs',
            options={'verbose_name': 'Consultant'},
        ),
        migrations.AlterModelOptions(
            name='domaine',
            options={'verbose_name': 'Secteur Client'},
        ),
        migrations.AlterModelOptions(
            name='experiences',
            options={'verbose_name': 'Intervention'},
        ),
        migrations.AddField(
            model_name='projet',
            name='benefClient',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projet',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AddField(
            model_name='projet',
            name='dateDebut',
            field=models.DateField(null=True, verbose_name='date de début du Projet'),
        ),
        migrations.AddField(
            model_name='projet',
            name='dateFin',
            field=models.DateField(null=True, verbose_name='date de fin du Projet'),
        ),
        migrations.AddField(
            model_name='projet',
            name='livrables',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projet',
            name='resumeProjet',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projet',
            name='BUProjet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collab.BU'),
        ),
    ]
