# Generated by Django 3.0.5 on 2020-05-26 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collab', '0012_auto_20200526_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='gestionManagerialeProjet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateField(null=True, verbose_name='date de début de la gestion du Projet')),
                ('dateFin', models.DateField(null=True, verbose_name='date de fin de la gestion du Projet')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='gestionCommercialeProjet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateField(null=True, verbose_name='date de début de la gestion commerciale du Projet')),
                ('dateFin', models.DateField(null=True, verbose_name='date de fin de la gestion commerciale du Projet')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='gestionCommerciale',
            field=models.ManyToManyField(to='collab.gestionCommercialeProjet'),
        ),
        migrations.AddField(
            model_name='projet',
            name='gestionManageriale',
            field=models.ManyToManyField(to='collab.gestionManagerialeProjet'),
        ),
    ]
