# Generated by Django 3.0.5 on 2020-05-26 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0013_auto_20200526_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collab.client'),
        ),
    ]
