# Generated by Django 3.0.5 on 2020-05-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0014_projet_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestioncommercialeprojet',
            name='dateFin',
            field=models.DateField(blank=True, null=True, verbose_name='date de fin de la gestion commerciale du Projet'),
        ),
        migrations.AlterField(
            model_name='gestionmanagerialeprojet',
            name='dateFin',
            field=models.DateField(blank=True, null=True, verbose_name='date de fin de la gestion du Projet'),
        ),
    ]
