# Generated by Django 3.0.5 on 2020-05-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0015_auto_20200526_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='dateFin',
            field=models.DateField(blank=True, null=True, verbose_name='date de fin du Projet'),
        ),
    ]
