# Generated by Django 3.0.5 on 2020-05-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0017_auto_20200526_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='expertiseSectorielle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='collaborateurs',
            name='tjm',
        ),
        migrations.AddField(
            model_name='collaborateurs',
            name='dateArrivee',
            field=models.DateField(null=True, verbose_name="date d'arrivée chez Themis"),
        ),
        migrations.AddField(
            model_name='collaborateurs',
            name='dateSortie',
            field=models.DateField(blank=True, null=True, verbose_name='date de sortie de chez Themis'),
        ),
        migrations.AddField(
            model_name='collaborateurs',
            name='grade',
            field=models.CharField(choices=[('1', 'Consultant Junior'), ('2', 'Consultant')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='collaborateurs',
            name='expertiseSectorielle',
            field=models.ManyToManyField(to='collab.expertiseSectorielle'),
        ),
    ]
