# Generated by Django 3.0.5 on 2020-05-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0018_auto_20200526_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateurs',
            name='expSignificative1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='collaborateurs',
            name='expSignificative2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='collaborateurs',
            name='expSignificative3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='collaborateurs',
            name='expSignificative4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='collaborateurs',
            name='expSignificative5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
