# Generated by Django 3.0.5 on 2020-05-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0019_auto_20200526_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateurs',
            name='clientPrincipaux',
            field=models.ManyToManyField(to='collab.client'),
        ),
    ]
