# Generated by Django 3.0.5 on 2020-05-26 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0020_collaborateurs_clientprincipaux'),
    ]

    operations = [
        migrations.CreateModel(
            name='formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(max_length=500)),
                ('ecole', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='collaborateurs',
            name='formation',
        ),
        migrations.CreateModel(
            name='obtentionFormation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateObtention', models.DateField(null=True, verbose_name="date d'obtention du diplome ou certification")),
                ('formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collab.formation')),
            ],
        ),
        migrations.AddField(
            model_name='collaborateurs',
            name='formation',
            field=models.ManyToManyField(to='collab.obtentionFormation'),
        ),
    ]
