# Generated by Django 3.0.5 on 2020-05-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0021_auto_20200526_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='niveauIntervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='collaborateurs',
            name='niveauxIntervention',
            field=models.ManyToManyField(to='collab.niveauIntervention'),
        ),
    ]
