# Generated by Django 3.0.5 on 2020-05-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0022_auto_20200526_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguesParlee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('niveau', models.CharField(choices=[('D', 'Debutant'), ('C', 'Courant'), ('B', 'Bilingue')], default='D', max_length=1)),
            ],
        ),
    ]
