# Generated by Django 3.0.5 on 2020-05-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0023_languesparlee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborateurs',
            name='langues',
        ),
        migrations.AddField(
            model_name='collaborateurs',
            name='langues',
            field=models.ManyToManyField(to='collab.LanguesParlee'),
        ),
    ]
