# Generated by Django 3.0.5 on 2020-05-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0024_auto_20200526_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateurs',
            name='dateDeNaissance',
            field=models.DateField(blank=True, null=True, verbose_name='date de naissance du consultant'),
        ),
    ]
