# Generated by Django 3.0.5 on 2020-05-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0025_collaborateurs_datedenaissance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='langue',
        ),
    ]
