# Generated by Django 3.0.5 on 2020-05-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0028_auto_20200529_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateurs',
            name='grade',
            field=models.CharField(choices=[('1', 'Consultant'), ('2', 'Manager'), ('3', 'Responsable Commercial'), ('4', 'Chargé de Recrutement'), ('5', 'Directeur')], default='1', max_length=1),
        ),
    ]
