# Generated by Django 3.0.5 on 2020-05-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0029_auto_20200529_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateurs',
            name='grade',
            field=models.CharField(choices=[('1', 'Junior'), ('2', 'Confirmé'), ('3', 'Sénior'), ('4', 'Expert')], default='1', max_length=1),
        ),
    ]
