# Generated by Django 3.0.5 on 2020-05-29 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0032_auto_20200529_1205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='domaine',
        ),
        migrations.RemoveField(
            model_name='experiences',
            name='client',
        ),
        migrations.RemoveField(
            model_name='experiences',
            name='contexteMission',
        ),
        migrations.RemoveField(
            model_name='experiences',
            name='nbJourHomme',
        ),
        migrations.RemoveField(
            model_name='experiences',
            name='niveauIntervention',
        ),
        migrations.AddField(
            model_name='experiences',
            name='employeurIntervention',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='experiences',
            name='mandataire',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='experiences',
            name='pourcentageIntervention',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='experiences',
            name='resumeIntervention',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='experiences',
            name='service',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='descriptifMission',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='environnementMission',
            field=models.TextField(default=''),
        ),
    ]
