# Generated by Django 3.0.7 on 2020-06-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0035_auto_20200608_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Methodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='collaborateurs',
            name='methodologie',
        ),
        migrations.AddField(
            model_name='collaborateurs',
            name='methodologie',
            field=models.ManyToManyField(to='collab.Methodo'),
        ),
    ]
