# Generated by Django 3.0.7 on 2020-06-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0036_auto_20200610_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiences',
            name='employeurIntervention',
        ),
        migrations.AddField(
            model_name='experiences',
            name='missionThemis',
            field=models.BooleanField(default=True),
        ),
    ]
