# Generated by Django 3.0.7 on 2020-06-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0037_auto_20200610_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='projetThemis',
            field=models.BooleanField(default=True),
        ),
    ]
