# Generated by Django 3.0.7 on 2020-06-10 10:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0040_auto_20200610_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateurs',
            name='codePostal',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateurs',
            name='dateArrivee',
            field=models.DateField(blank=True, null=True, verbose_name="date d'arrivée chez Themis"),
        ),
        migrations.AlterField(
            model_name='collaborateurs',
            name='grade',
            field=models.CharField(blank=True, choices=[('1', 'Junior'), ('2', 'Confirmé'), ('3', 'Sénior'), ('4', 'Expert')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateurs',
            name='mail',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateurs',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateurs',
            name='texteIntroductifCv',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
