# Generated by Django 3.0.7 on 2020-06-10 10:59

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0043_auto_20200610_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='descriptifMission',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='mandataire',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='pourcentageIntervention',
            field=models.IntegerField(blank=True, default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='resumeIntervention',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='service',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
