# Generated by Django 3.0.7 on 2020-06-10 11:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0044_auto_20200610_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='environnementMission',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
