# Generated by Django 3.0.7 on 2020-06-10 11:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0045_auto_20200610_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='environnementMission',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='benefClient',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='projet',
            name='contexteMission',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='gestionCommerciale',
            field=models.ManyToManyField(blank=True, to='collab.gestionCommercialeProjet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='gestionManageriale',
            field=models.ManyToManyField(blank=True, to='collab.gestionManagerialeProjet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='livrables',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='nbJourHomme',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='resumeProjet',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
