# Generated by Django 3.0.7 on 2020-06-10 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0046_auto_20200610_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='experiencesLiees',
        ),
        migrations.AddField(
            model_name='experiences',
            name='projetDeLaMission',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='collab.projet'),
        ),
    ]
