# Generated by Django 3.0.7 on 2020-06-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0048_auto_20200610_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateurs',
            name='nbAnneeExperience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
