# Generated by Django 3.0.7 on 2020-06-12 08:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0051_auto_20200610_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='domaineClient',
            field=models.CharField(choices=[('1', 'Activités immobilières '), ('2', 'Agriculture'), ('3', 'Agroalimentaire'), ('4', 'Armée, sécurité'), ('5', 'Art, Design'), ('6', 'Assurance'), ('6B', 'Assurance de Personne'), ('7', 'Audiovisuel, Spectacle, Cinéma'), ('8', 'Audit, Études et conseils, Expertise'), ('9', 'Automobile et  réparation automobile '), ('10', 'Banque'), ('11', 'Bois / Papier / Carton'), ('12', 'BTP, Architecture'), ('13', 'Chimie / Parachimie'), ('14', 'Commerce / Négoce'), ('15', 'Commerce du jeu '), ('16', 'Construction aéronautique, ferroviaire et navale'), ('17', "Culture, Artisanat d'art"), ('18', 'Distribution'), ('19', 'Droit, justice'), ('20', 'e-commerce'), ('21', 'Édition / imprimerie / reproduction / Communication / Multimédia'), ('22', 'Edition, Journalisme'), ('23', 'Électricité'), ('24', 'Electronique, Electrotechnique'), ('25', 'Energie'), ('26', 'Enseignement et éducation '), ('27', 'Environnement'), ('28', 'Fonction publique'), ('29', 'Hôtellerie , Café, Tabac et Restauration'), ('30', 'Imprimerie'), ('3D', 'Industrie'), ('31', 'Industrie du tabac '), ('32', 'Industrie pharmaceutique'), ('33', 'Informatique, Numérique et Réseaux'), ('34', 'Logistique'), ('35', 'Machines et équipements'), ('36', 'Maintenance, entretien'), ('37', 'Marketing, publicité, Communication'), ('38', 'Matériaux de construction, , Transformations'), ('39', 'Métallurgie'), ('40', 'Mode / Textile / Habillement / Chaussure'), ('41', 'Plastique / Caoutchouc'), ('42', 'Poste et télécommunications '), ('43', 'Recherche et développement '), ('44', 'Récupération '), ('45', 'Santé, médical'), ('46', 'Services aux entreprises'), ('47', 'Social, Services à la personne'), ('48', 'Sport et loisirs'), ('49', 'Tourisme'), ('50', 'Transports')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='collaborateurs',
            name='nomCollaborateur',
            field=models.CharField(max_length=200, verbose_name='Nom du Collaborateur'),
        ),
        migrations.AlterField(
            model_name='collaborateurs',
            name='texteIntroductifCv',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Il s’agit du texte introductif que l’on retrouve en première page du DC au-dessous du titre introductif', null=True),
        ),
        migrations.AlterField(
            model_name='collaborateurs',
            name='titreCollaborateur',
            field=models.CharField(help_text='Il s’agit du titre que l’on retrouve en première page du DC au-dessus du texte introductif (ex : Consultant AMOA)', max_length=200),
        ),
    ]
