# Generated by Django 3.0.7 on 2020-06-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0054_auto_20200612_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='missionThemis',
            field=models.BooleanField(default=True, help_text='Décochez la coche, s’il s’agit d’une mission pour le compte d’une autre société', verbose_name='Mission Thémis'),
        ),
    ]
