# Generated by Django 3.0.7 on 2020-06-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0055_auto_20200612_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='employeur',
            field=models.CharField(blank=True, default='', help_text='Dans le cas où la coche est décochée, merci d’indiquer pour le compte de quelle société avez-vous effectué cette intervention ?', max_length=300, verbose_name='Employeur lors de l’intervention'),
        ),
    ]
