# Generated by Django 3.0.7 on 2020-06-12 09:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0056_auto_20200612_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='demarcheenjeux',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Merci d’y ajouter aussi l’environnement technique de la mission', null=True, verbose_name='Démarche et réalisations'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='BUProjet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collab.BU', verbose_name='BU rattaché au projet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='benefClient',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Se mettre à la place du client et lister les bénéfices obtenus', null=True, verbose_name='Bénéfices Client'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='contexteMission',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Contexte et Enjeux'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='gestionCommerciale',
            field=models.ManyToManyField(blank=True, help_text='Indiquez le nom du Commercial responsable du projet', to='collab.gestionCommercialeProjet', verbose_name='Gestion Commerciale'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='gestionManageriale',
            field=models.ManyToManyField(blank=True, help_text='Indiquez le nom du Manager responsable du projet', to='collab.gestionManagerialeProjet', verbose_name='Gestion Managériale'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='livrables',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Listez les livrables sous forme de bullet point', null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='nbJourHomme',
            field=models.IntegerField(blank=True, verbose_name='Nombre de jours hommes'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='nomProjet',
            field=models.CharField(max_length=300, verbose_name='Nom du projet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='projetThemis',
            field=models.BooleanField(default=True, help_text='Décochez la coche, s’il s’agit d’un projet pour le compte d’une autre société', verbose_name='Projet Thémis'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='resumeProjet',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Bref résumé du projet en 3 lignes', null=True, verbose_name='Résumé du Projet'),
        ),
    ]
