# Generated by Django 2.2.5 on 2020-06-16 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0057_auto_20200612_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='BUProjet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collab.BU', verbose_name='BU rattaché au projet'),
        ),
    ]
