# Generated by Django 2.2.5 on 2020-06-16 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0058_auto_20200616_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='BUProjet',
            field=models.ForeignKey(blank=True, help_text='Indiquez le nom de la BU s’il s’agit d’une mission Thémis', null=True, on_delete=django.db.models.deletion.SET_NULL, to='collab.BU', verbose_name='BU rattaché au projet'),
        ),
    ]
