# Generated by Django 2.2.5 on 2020-06-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0059_auto_20200616_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='employeur',
            field=models.CharField(blank=True, default='', help_text=' Dans le cas où la coche « Mission Thémis » est décochée, merci d’indiquer pour le compte de quelle société avez-vous effectué cette intervention ?', max_length=300, verbose_name='Employeur lors de l’intervention'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='service',
            field=models.CharField(blank=True, default='', help_text='Indiquez la Direction ou le Service du client dans lequel le consultant est intervenu', max_length=300, verbose_name='Direction ou Service Client'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, null=True),
        ),
    ]
