# Generated by Django 2.2.5 on 2020-06-18 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0060_auto_20200616_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateurs',
            name='nbAnneeExperience',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Nb d’année d’expérience'),
        ),
    ]
