# Generated by Django 2.2.5 on 2020-06-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0061_auto_20200618_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateurs',
            name='formation',
            field=models.ManyToManyField(blank=True, to='collab.obtentionFormation', verbose_name='Formations & Certifications'),
        ),
    ]
