# Generated by Django 2.2.5 on 2020-06-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0064_auto_20200622_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateurs',
            name='grade',
            field=models.CharField(blank=True, choices=[('1', 'Consultant Junior'), ('2', 'Consultant'), ('3', 'Consultant Sénior'), ('4', 'Runner Manager'), ('5', 'Manager'), ('5', 'Directeur')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='nbJourHomme',
            field=models.IntegerField(blank=True, default=0, verbose_name='Nombre de jours hommes'),
        ),
    ]
