# Generated by Django 2.2.5 on 2020-06-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0065_auto_20200623_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborateurs',
            name='nbAnneeExperience',
        ),
        migrations.AddField(
            model_name='collaborateurs',
            name='dateDebutExpPro',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début de carrière'),
        ),
    ]
